// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.DatabaseContext;

#nullable disable

namespace Thermostat.DataAccessLayer.Migrations
{
    [DbContext(typeof(EnvMeasurementsWriteSqlDbContext))]
    [Migration("20250811201230_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.DatabaseContext.RuleDefinitionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RuleEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RuleEntityId")
                        .IsUnique();

                    b.ToTable("RuleDefinitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("90a6909d-5d14-4220-b035-b60926edd2d7"),
                            RuleEntityId = new Guid("90a6909d-5d14-4220-b035-b60926edd2d6"),
                            Type = "GreaterThan"
                        });
                });

            modelBuilder.Entity("Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.Entities.ActionDefinitionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RuleEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RuleEntityId")
                        .IsUnique();

                    b.ToTable("ActionDefinitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("90a6909d-5d14-4220-b035-b60926edd2d5"),
                            CreatedAt = new DateTime(2015, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RuleEntityId = new Guid("90a6909d-5d14-4220-b035-b60926edd2d6"),
                            Type = "HeatingControl"
                        });
                });

            modelBuilder.Entity("Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.Entities.ActionParameterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActionDefinitionEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ParameterName");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ParameterValue");

                    b.HasKey("Id");

                    b.HasIndex("ActionDefinitionEntityId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_ActionParameters_Name");

                    b.ToTable("ActionParameters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("90a6909d-5d14-4220-b035-b60926edd2d7"),
                            ActionDefinitionEntityId = new Guid("90a6909d-5d14-4220-b035-b60926edd2d5"),
                            Name = "Command",
                            Type = "System.String",
                            Value = "Stop"
                        });
                });

            modelBuilder.Entity("Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.Entities.HeatingSettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("HumidityAlertThreshold")
                        .HasColumnType("float");

                    b.Property<double>("TempHigh")
                        .HasColumnType("float");

                    b.Property<double>("TempLow")
                        .HasColumnType("float");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HeatingSettings", (string)null);
                });

            modelBuilder.Entity("Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.Entities.HouseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Houses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("90a6909d-5d14-4220-b035-b60926edd2d4"),
                            Name = "Default House"
                        });
                });

            modelBuilder.Entity("Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.Entities.RuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("HouseRootId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HouseRootId");

                    b.HasIndex("SensorId");

                    b.ToTable("Rules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("90a6909d-5d14-4220-b035-b60926edd2d6"),
                            Enabled = true,
                            HouseRootId = new Guid("90a6909d-5d14-4220-b035-b60926edd2d4"),
                            Name = "Stop Heating Rule if temp >= 23°C",
                            SensorId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        });
                });

            modelBuilder.Entity("Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.Entities.RuleParameterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("RuleDefinitionEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RuleDefinitionEntityId");

                    b.ToTable("RuleParameters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("90a6909d-5d14-4220-b035-b60926edd2d9"),
                            Name = "Threshold",
                            RuleDefinitionEntityId = new Guid("90a6909d-5d14-4220-b035-b60926edd2d7"),
                            Type = "System.Double",
                            Value = "23.0"
                        });
                });

            modelBuilder.Entity("Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.Entities.SensorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HouseRootId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("RoomArea")
                        .HasColumnType("float")
                        .HasColumnName("RoomArea");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RoomName");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RoomType");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SensorType");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MeasurementUnit");

                    b.HasKey("Id");

                    b.HasIndex("HouseRootId");

                    b.ToTable("Sensors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            HouseRootId = new Guid("90a6909d-5d14-4220-b035-b60926edd2d4"),
                            RoomArea = 20.0,
                            RoomName = "Living Room",
                            RoomType = "LivingRoom",
                            Type = "Temperature",
                            Unit = "Celsius"
                        },
                        new
                        {
                            Id = new Guid("b1c2d3e4-f5a6-7890-abcd-ef1234567890"),
                            HouseRootId = new Guid("90a6909d-5d14-4220-b035-b60926edd2d4"),
                            RoomArea = 15.0,
                            RoomName = "Bedroom",
                            RoomType = "Bedroom",
                            Type = "Humidity",
                            Unit = "Percent"
                        });
                });

            modelBuilder.Entity("Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.Entities.SensorMeasurementEntity", b =>
                {
                    b.Property<Guid>("HouseRootId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SensorEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("HouseRootId", "SensorEntityId", "Timestamp");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_SensorMeasurements_Timestamp");

                    b.HasIndex("SensorEntityId", "Timestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_SensorMeasurements_SensorId_Timestamp");

                    b.ToTable("SensorMeasurements", (string)null);
                });

            modelBuilder.Entity("Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.DatabaseContext.RuleDefinitionEntity", b =>
                {
                    b.HasOne("Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.Entities.RuleEntity", null)
                        .WithOne("RuleDefinition")
                        .HasForeignKey("Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.DatabaseContext.RuleDefinitionEntity", "RuleEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.Entities.ActionDefinitionEntity", b =>
                {
                    b.HasOne("Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.Entities.RuleEntity", null)
                        .WithOne("ActionDefinition")
                        .HasForeignKey("Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.Entities.ActionDefinitionEntity", "RuleEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.Entities.ActionParameterEntity", b =>
                {
                    b.HasOne("Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.Entities.ActionDefinitionEntity", "ActionEntity")
                        .WithMany("Parameters")
                        .HasForeignKey("ActionDefinitionEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionEntity");
                });

            modelBuilder.Entity("Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.Entities.RuleEntity", b =>
                {
                    b.HasOne("Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.Entities.HouseEntity", null)
                        .WithMany("Rules")
                        .HasForeignKey("HouseRootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.Entities.SensorEntity", null)
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.Entities.RuleParameterEntity", b =>
                {
                    b.HasOne("Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.DatabaseContext.RuleDefinitionEntity", null)
                        .WithMany("Parameters")
                        .HasForeignKey("RuleDefinitionEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.Entities.SensorEntity", b =>
                {
                    b.HasOne("Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.Entities.HouseEntity", null)
                        .WithMany("Sensors")
                        .HasForeignKey("HouseRootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.Entities.SensorMeasurementEntity", b =>
                {
                    b.HasOne("Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.Entities.HouseEntity", null)
                        .WithMany()
                        .HasForeignKey("HouseRootId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.Entities.SensorEntity", "Sensor")
                        .WithMany("Measurements")
                        .HasForeignKey("SensorEntityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.DatabaseContext.RuleDefinitionEntity", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.Entities.ActionDefinitionEntity", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.Entities.HouseEntity", b =>
                {
                    b.Navigation("Rules");

                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.Entities.RuleEntity", b =>
                {
                    b.Navigation("ActionDefinition")
                        .IsRequired();

                    b.Navigation("RuleDefinition")
                        .IsRequired();
                });

            modelBuilder.Entity("Thermostat.DataAccessLayer.EFData.Infrastructure.HeatingEnvironmentalConditions.Entities.SensorEntity", b =>
                {
                    b.Navigation("Measurements");
                });
#pragma warning restore 612, 618
        }
    }
}
